apiVersion: v1
kind: Secret
metadata:
  name: k8s-test-db01-secret
type: Opaque
stringData:
  password: YOUR_DATABASE_PASSWORD
  ssh_public_key: YOUR_SSH_KEY
---
apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
  # This name that will be used within the kubernetes cluster
  name: k8s-test-db01
spec:
  # Name of the NDBServer resource created earlier
  ndbRef: ndb
  isClone: false
  # Database instance specific details (that is to be provisioned)
  databaseInstance:
    # Cluster id of the cluster where the Database has to be provisioned
    # Can be fetched from the GET /clusters endpoint
    clusterId: "195520f0-1f4b-42c7-ac51-a9a28018bfcb"
    # The database instance name on NDB
    name: "rd-k8s_test_db01"
    # The description of the database instance
    description: Test DB Deployment from K8s
    # Names of the databases on that instance
    databaseNames:
      - database_one
    # Credentials secret name for NDB installation
    # data: password, ssh_public_key
    credentialSecret: k8s-test-db01-secret
    size: 10
    timezone: "UTC"
    type: postgres

    # You can specify any (or none) of these types of profiles: compute, software, network, dbParam
    # If not specified, the corresponding Out-of-Box (OOB) profile will be used wherever applicable
    # Name is case-sensitive. ID is the UUID of the profile. Profile should be in the "READY" state
    # "id" & "name" are optional. If none provided, OOB may be resolved to any profile of that type
    profiles:
      compute:
        name: "DEFAULT_OOB_COMPUTE"
        # id: ""
      # A Software profile is a mandatory input for closed-source engines: SQL Server & Oracle
      software:
        name: "POSTGRES_10.4_OOB"
        # id: ""
      network:
        name: "POSTGRESQL"
        # id: ""
      dbParam:
        name: "DEFAULT_POSTGRES_PARAMS"
        # id: ""
      # Only applicable for MSSQL databases
      # dbParamInstance:
      #   name: ""
      #   id: ""
    timeMachine:                        # Optional block, if removed the SLA defaults to NONE
      sla : "DEFAULT_OOB_BRONZE_SLA"
      dailySnapshotTime:   "12:34:56"   # Time for daily snapshot in hh:mm:ss format
      snapshotsPerDay:     1            # Number of snapshots per day
      logCatchUpFrequency: 90           # Frequency (in minutes)
      weeklySnapshotDay:   "WEDNESDAY"  # Day of the week for weekly snapshot
      monthlySnapshotDay:  24           # Day of the month for monthly snapshot
      quarterlySnapshotMonth: "Jan"     # Start month of the quarterly snapshot
    additionalArguments:                # Optional block, can specify additional arguments that are unique to database engines.
      listener_port: "5432"