kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: claim-test-volumes
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 13Gi
   storageClassName: nutanix-volumes