apiVersion: v1
kind: Secret
metadata:
 name: nutanix-csi-files-credentials
 namespace: ntnx-system
stringData:
# Provide Nutanix Prism Element credentials which is a default UI credential separated by colon in "key:".
# Provide Nutanix File Server credentials which is a REST API user created on File server UI separated by colon in "files-key:".
  key: "PC_IP_ADDRESS:9440:admin:PC_ADMIN_PASSWORD"
  files-key: "FILE_SERVER_FQDN:admin:PC_ADMIN_PASSWORD"
---
allowVolumeExpansion: true
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: nutanix-dynamicfile
provisioner: csi.nutanix.com
parameters:
    csi.storage.k8s.io/node-publish-secret-name: nutanix-csi-files-credentials
    csi.storage.k8s.io/node-publish-secret-namespace: ntnx-system
    csi.storage.k8s.io/controller-expand-secret-name: nutanix-csi-files-credentials
    csi.storage.k8s.io/controller-expand-secret-namespace: ntnx-system
    dynamicProv: ENABLED
    nfsServerName: FILE_SERVER_NAME
    csi.storage.k8s.io/provisioner-secret-name: nutanix-csi-files-credentials
    csi.storage.k8s.io/provisioner-secret-namespace: ntnx-system
    storageType: NutanixFiles
    squashType: root-squash
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
